name = "kaiwa-llm-mock"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"

[build.environment]
NODE_VERSION = "20"

# Pages specific configuration
# Build output directory: .vercel/output/static
